Add support for downloading the chromedriver after installation
giggio/node-chromedriver pull request #332
Opened 2021-11-06 23:27 UTC by niehusst

This is the same code changes as #278 (all substantial code changes are thanks to @r3pwn) but without any of the refactoring that made it seem like a bigger PR than it actually was. Hopefully, this will be easier to review.

Using the `.download` async function, we can now do things like

```
await chromedriver.download();
```
before any tests get run.

Additionally, some options are supported.
We can pass in `download_version` or `cdn_url` like such:
```
await chromedriver.download({cdn_url: "http://localhost", download_version: "84"});
```
download_version is able to be passed in as the full version of chrome ("84.0.4147.105") or just the major version ("84")

I believe this is the functionality requested by @HaimBendanan in issue #256

2021-11-06 23:29 UTC, niehusst commented on install.js
> +      if (detect_chromedriver_version === 'true') {
I only indented the install function execution with this `if`, but the diff doesn't do a good job of showing that

2021-11-08 15:26 UTC, giggio requested changes
Hi, @niehusst! Thanks for the PR, it is much easier to review now.
I think we can improve it a bit. I few there is a bit of feature envy going on in the chromedriver.js file, it is using a lot of things from install.js.
I'd prefer that the installation functions be moved into chromedriver.js, and install.js would then use those functions, and continued to be a install only script, not used in the module itself.
This would also eliminate a bit of code duplication that is showing up at the current iteration.

2021-11-09 06:01 UTC, niehusst commented
Good idea @giggio. Hopefully this little refactor cleans things up a bit without making the PR too convoluted.

2021-11-09 15:47 UTC, niehusst commented
The CI build has failed, but the error logs aren't the most helpful, so I'm not really sure what the problem is. Some of the failures look like they're git permissions related, and others seem to have stalled during what looks like environment setup? Lmk if you can make any more sense of the errors.

2021-11-21 22:11 UTC, niehusst commented
@giggio did you ever get a chance to look at this again?

2021-11-30 11:22 UTC, closed without merging