Fix apple silicon arch for newer chromedriver build schema
giggio/node-chromedriver pull request #386
Opened 2022-09-28 21:43 UTC by sarkis

Fixes #384 with backwards compatibility

2022-09-28 21:49 UTC, sarkis commented on install.js
> +    if (compareVersions(chromedriver_version, '106.0.5249.61') < 0) {
This returns `-1` when `chromedriver_version` < 106.0.5249.61

2022-09-28 22:05 UTC, zarko-tg commented
Looks good in principle.
How do you test the cases from command line, from within the project/folder?

2022-09-28 22:27 UTC, zarko-tg commented
Thanks, looks fine for me but I guess it wouldn't hurt if someone more experienced with the project checks things.

2022-09-28 22:32 UTC, zarko-tg commented on install.js
> +    if (compareVersions(chromedriver_version, '106.0.5249.61') < 0) {
Not being too transparent code-wise, I suppose this will work as expected for chromedriver_version === 'LATEST' ?

2022-09-29 13:41 UTC, giggio requested changes
Please see comments.

2022-09-29 13:41 UTC, giggio commented on install.js
> +let platform = '';
Why was this moved and why isn't it const, anymore? If there is no reason, please revert.

2022-09-29 13:41 UTC, giggio commented on install.js
> +      throw new Error('Unexpected return code from sysctl: ' + proc.status);
Please remove all changes which are style only.

2022-09-29 13:41 UTC, giggio commented on install.js
> +    if (compareVersions(chromedriver_version, '106.0.5249.61') < 0) {
When it gets here `chromedriver_version` is already the correct version.

2022-09-29 14:23 UTC, sarkis commented on install.js
> +let platform = '';
Since we are setting the provider on MacOS to different strings based on the version of chromedriver_version this needs to be moved down after the code that computes the version to be installed.

2022-09-29 14:34 UTC, giggio commented on install.js
> +let platform = '';
Ok! But it can still be `const`, right?

2022-09-29 14:47 UTC, sarkis commented on install.js
> +let platform = '';
I might be missing something, I did try to leave this a constant - the issue seems to be a scope issue as other functions such as `downloadFile` for example need the `platform` var: https://github.com/giggio/node-chromedriver/blob/8a3b83779e337de6b5351bc50ded143c779c45ef/install.js#L113

So the only way I see that continuing to work is changing the global scope declaration to a `let` and then further down in `install` when the version is computed we run the `validatePlatform()` function.

2022-09-29 15:17 UTC, sarkis commented on install.js
> +      throw new Error('Unexpected return code from sysctl: ' + proc.status);
Done - reverted any style and formatting changes.

2022-09-29 20:04 UTC, jlaustill approved these changes
This is blocking our work with our newer employees with M1 MacBooks; thank you for taking the time to PR this.

2022-09-29 22:30 UTC, giggio commented on install.js
> +let platform = '';
Yes, the scope changes if you try that. I'll leave it like that for now, so we can fix this, and later will work on refactoring it.

2022-09-29 22:34 UTC, giggio approved these changes
this is good, i'll just wait for the build to complete and merge it.

2022-09-29 22:36 UTC, merged